---    
artifacts:    
  files: imagedefinitions.json   
phases:    
  build:    
    commands:    
      - "echo Build started on `date`"   
      - "echo Building the Docker image..."   
      - "docker build -t $REPOSITORY_URI:latest ."   
      - "docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG"   
  post_build:    
    commands:    
      - "echo Build completed"   
      - "echo Pushing the Docker images..."   
      - "docker push $REPOSITORY_URI:latest"   
      - "docker push $REPOSITORY_URI:$IMAGE_TAG"   
      - "echo Writing definitions file..."   
      - "printf '[{\"name\":\"phtml\",\"imageUri\":\"%s\"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json"   
  pre_build:    
    commands:    
      - "echo Logging in to Amazon ECR..."   
      - "aws --version"   
      - "$(aws ecr get-login --region us-east-2 --no-include-email)"   
      - REPOSITORY_URI=026033341139.dkr.ecr.us-east-2.amazonaws.com/hello-world   
      - "COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)"   
      - "IMAGE_TAG=${COMMIT_HASH:=latest}"   
version: 0.2 
